{% set name = "pyqmix" %}
{% set version = "2021.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02d22b0b39afb0e2af4323a10906ae98648531d6c1db2b187549503fee17d592

build:
  number: 4
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vvv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - cffi
    - ruamel.yaml
    - appdirs
    - pywin32  # [win]

test:
  imports:
    - pyqmix

about:
  home: https://github.com/psyfood/pyqmix
  license: GPL-3.0-only
  license_file: LICENSE
  summary: A wrapper for the Cetoni Qmix SDK
  description: |
    This Python package wraps the Cetoni Qmix pump and valve interface DLLs
    using CFFI.
  doc_url: https://pyqmix.readthedocs.io/
  dev_url: https://github.com/psyfood/pyqmix

extra:
  recipe-maintainers:
    - hoechenberger
    - ArndalAndersen
