appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: miPidwkfm1eMzoTEXexQfSd163pleyYjcgujOYt98b3gB7sDhi/bF/NS7dou0hkPo/aje7M3i0+uFFo1q4Lprrp/nE79EvbkmXaR5slRMLozvUGKCu9wNuAsuAP3ymlTXvC6IEdJvADzP6o1lwb7eNf2vJIn9TQroL0SVH9CX7VK/ywjy26NCkwo8aWGkV0phEz7hJZMTphVldTsMZ0Xi0n0iduSD+7Xrbrk0Z4ZiIRPuU+ImXWO8tYlGib8+YH7YGXPMyI1dPdzf8ELEW1akHxNBJ0Zg00t2kqvCytDDsLbVHMN8ejrrWATwFF/4+rYOTrR3Lqv8X0mgeKLHoeGJ27lkDWgX2z6R6tVvn6Q/gtkzYDi7374tFRYoSLxRfDmnXFM9R2qLsB6kQlorHRKRT+pLeK1YgGN1UNo7ZWKyHo/7iywqZoPJryJfq1J8ih99wbxeVohnmdKAoJ4g5BelxZsPkxTD8HXvB7vUDu0g4MuUiWPVd92EXlGD8utszFSFsccsm5YS0vQD2x5mHZGtsOz7bt+qwbIruFscElXogSEe3xImK7Lql0zo7bUyqxB0wyEy/qGBflqQ+uSdZo/IYPlDZOxbm9TjOL0f1c0D+f4Rb0ehsPW9bNzChvWfL6viVS3w3PaZbkd45HZrnTa4OgZoJMtqu0W73XQdy0Xuew=}
provider:
  win: azure
conda_forge_output_validation: true
